/* Drop-in live mailbox layer. Existing dashboard behavior is preserved; Command Hub v2 is loaded in addition. */
(function(){
  let ACCOUNT_ORDER=['acc-hr','acc-main','acc-sales-net','acc-sales-way'];
  const ACCOUNT_META={'acc-hr':{name:'HR',address:'hr@salyant.co.uk'},'acc-main':{name:'Main',address:'yash@salyant.co.uk'},'acc-sales-net':{name:'Sales',address:'automate@salyant.net'},'acc-sales-way':{name:'Sales Way',address:'ai@thesalyantway.co.uk'}};
  function normalizeAccounts(response){const rows=Array.isArray(response)?response:Array.isArray(response?.accounts)?response.accounts:[];const EMAIL_TO_ID={'hr@salyant.co.uk':'acc-hr','yash@salyant.co.uk':'acc-main','automate@salyant.net':'acc-sales-net','ai@thesalyantway.co.uk':'acc-sales-way'};const ids=rows.map(x=>x.id).filter(Boolean); if(ids.length) ACCOUNT_ORDER=ids; return rows.map(account=>{const addresses=Array.isArray(account.addr)?account.addr:Array.isArray(account.emailAddress)?account.emailAddress:[];const email=account.email||account.emailAddress||addresses.find(x=>x.isPrimary)?.mailId||addresses[0]?.mailId||account.address||'';const id=EMAIL_TO_ID[email]||account.id||null;return {...(ACCOUNT_META[id]||{}),...account,id}}).filter(a=>a.id)}
  function normalizeMail(response){if(Array.isArray(response))return response;if(Array.isArray(response?.messages))return response.messages;if(Array.isArray(response?.data))return response.data;return []}
  window.SalyantLive={ACCOUNT_ORDER,ACCOUNT_META,async loadAccounts(){return normalizeAccounts(await window.SalyantAPI.accounts())},async loadMailbox(account,limit=25){if(!account)throw new Error('Mailbox account is required.');return normalizeMail(await window.SalyantAPI.mail(account,limit))},async loadAllMail(limit=25){const r={};await Promise.all(ACCOUNT_ORDER.map(async a=>r[a]=await window.SalyantLive.loadMailbox(a,limit)));return r},async send(payload){return window.SalyantAPI.send(payload)},async chat(message,account='acc-main',sessionId='director-session'){return window.SalyantAPI.chat(message,account,sessionId)},async health(){return window.SalyantAPI.health()}};
  window.SalyantLiveState={accounts:[],mail:{},healthy:false,loading:false,lastError:null};
  window.refreshSalyantLiveData=async function(){const state=window.SalyantLiveState;state.loading=true;state.lastError=null;try{state.accounts=await window.SalyantLive.loadAccounts();state.mail=await window.SalyantLive.loadAllMail(25);state.healthy=true;window.dispatchEvent(new CustomEvent('salyant-live-ready',{detail:state}));return state}catch(error){state.healthy=false;state.lastError=error;window.dispatchEvent(new CustomEvent('salyant-live-error',{detail:error}));throw error}finally{state.loading=false}};
  function loadSelfHeal(){if(document.getElementById('salyant-self-heal-loader'))return;const s=document.createElement('script');s.id='salyant-self-heal-loader';s.src='/js/salyant-self-heal.js';s.async=true;document.head.appendChild(s)}
  function loadCeoAutopilot(){if(document.getElementById('salyant-ceo-autopilot-loader'))return;const s=document.createElement('script');s.id='salyant-ceo-autopilot-loader';s.src='/js/salyant-ceo-autopilot.js';s.async=true;document.head.appendChild(s)}
  function loadControl(){if(document.getElementById('salyant-command-control-loader'))return;const s=document.createElement('script');s.id='salyant-command-control-loader';s.src='/js/salyant-command-control.js';s.async=true;document.head.appendChild(s)}
  function loadOpsMonitor(){if(document.getElementById('salyant-ops-monitor-loader'))return;const s=document.createElement('script');s.id='salyant-ops-monitor-loader';s.src='/js/salyant-ops-monitor.js';s.async=true;document.head.appendChild(s)}
  function boot(){loadSelfHeal();loadCeoAutopilot();loadControl();loadOpsMonitor();window.refreshSalyantLiveData().catch(()=>{})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
